import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Liên hệ",
  description: "Generated by create next app",
};

export default function ContactPage() {
  return <div className="container">Liên hệ</div>;
}
